name: Release
on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Build Extension Package
        run: |
          mkdir -p _build
          cp -r extension.js metadata.json stylesheet.css LICENSE README.md _build/
          cd _build && zip -qr "mouse-battery@seyhankokcu.github.io.zip" *
      
      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false
          files: ./_build/mouse-battery@seyhankokcu.github.io.zip
